### ISSUE TITLE
Support for Pytorch 1.1.0?

### ISSUE THREAD

**Issue by anhle-uet** [jpuigcerver/pytorch-baidu-ctc#7]

**Comment by zhubuz** [comment]
same question! got link error:
 import torch_baidu_ctc._C as _torch_baidu_ctc
ImportError: /home/user/miniconda3/envs/py3/lib/python3.6/site-packages/torch_baidu_ctc/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE
when use pytorch 1.1.0.

**Comment by jpuigcerver** [comment]
I'll build and release a new version compiled to work with PyTorch 1.1.0, meanwhile you can try to install the package from sources.

Either clone the GitHub repo and install from it, or use pip.
