### ISSUE TITLE
Need update for new version of Pytorch

### ISSUE THREAD

**Issue by anhle-uet** [jpuigcerver/pytorch-baidu-ctc#9]
Your work is great since the official implementation of Pytorch doesn't work for me. Could you release newer version that capable with Pytorch 1.2.0 and 1.3.0? Thanks alot!

**Comment by 1ytic** [comment]
One of the reasons why it does not work with new PyTorch is new CUDA 10.1. Here is the quote from the [release notes](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html):

> The non-sync definitions of warp shuffle functions ( __shfl, __shfl_up, __shfl_down, and __shfl_xor ) and warp vote functions (__any, __all, __ballot) have been removed when compilation is targeting devices with compute capability 7.x and higher.

There is one usage of `__shfl_down` in `warp-ctc/src/reduce.cu` which you can replace to `__shfl_down_sync`.

Unfortunately, the Baidu's ctc implementation depends on [ModernGPU](https://github.com/moderngpu/moderngpu), which has not been updated for a long time and also uses `__shfl` functions. Thus, you also have to patch `warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh`.

I will recommend you to use the official PyTorch implementation of [ctc_loss](https://pytorch.org/docs/stable/nn.html#ctcloss), even though I don’t like this spaghetti code [LossCTC.cu](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/LossCTC.cu).

It seems like after the bug fix [#27460](https://github.com/pytorch/pytorch/pull/27460) PyTorch's implementation is stable.

**Comment by anhle-uet** [comment]
@1ytic Well, I've tried many times, but the official implementation doesn't work for me.

@jpuigcerver Do you intend to continue to maintain this repo? :)

**Comment by jpuigcerver** [comment]
Dear users, since PyTorch now includes its own CTC implementation, I'd suggest to use it instead of Baidu's.

Unfortunately, I don't have the time to fix Baidu's implementation myself.
